spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/locexchange
      auto-index-creation: true
  rsocket.server:
    mapping-path: /rsocket
    transport: websocket
    port: 7000

distance.maximum.allowed: 10

logging:
  level:
    root: info

google-maps:
  api:
    key: randomkey
