server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/locexchange
      auto-index-creation: true

distance.maximum.allowed: 10

logging:
  level:
    root: info

google-maps:
  api:
    key: randomkey
